# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Develop Branch Build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: [self-hosted, devui]

    strategy:
      matrix:
        node-version: [22.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm i --force
      - name: Build for development environment
        run: npm run build:development
      - name: Clean destination directory
        run: sudo rm -rf /var/www/dexter/*
        # Adding a check to make sure we don't delete if the directory doesn't exist
        continue-on-error: true
      - name: Copy build files to server
        run: sudo cp -r build/* /var/www/dexter
